import { notFound } from 'next/navigation';
import { hasLocale } from 'next-intl';
import { routing } from 'configs/i18n/routing';
import { GoogleAnalytics } from 'context/GoogleAnalytics';
import { AppServerProvider } from 'provider/AppServerProvider';
import type { Metadata, Viewport } from 'next';
import '@/styles/globals.css';

export const metadata: Metadata = {
  title: 'next-stack',
  description: 'Generated by create next app',
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  viewportFit: 'cover',
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html lang={locale}>
      <head>
        <meta
          name="apple-mobile-web-app-title"
          content="next-stack"
        />
        <GoogleAnalytics />
      </head>
      <body>
        <AppServerProvider locale={locale}>{children}</AppServerProvider>
      </body>
    </html>
  );
}
